### ISSUE TITLE
Paramaterize `Protocol`

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/ecs-alb-target#9]
Normally, you're using an ALB as a reverse proxy for a backend service that's running on HTTP.

In my case, I had to wrap a 3rd party service that was using a self-signed SSL certificate.  It's also possible that someone might intentionally incorporate an SSL certificate into their backend service to provide more complete end-to-end encryption.

The ALB doesn't care whether that certificate is valid, but it is necessary to use the HTTPS protocol for both `Protocol` and, since this module defaults to the same port, `HealthCheckProtocol`.

**Comment by michaelwittig** [comment]
is this related to #10  ?

**Comment by ambsw-technology** [comment]
I don't know that person but it looks like they're using this issue as an opportunity to contribute.

**Comment by michaelwittig** [comment]
Great. I added a comment to the PR. Let's wait for a response.

**Comment by michaelwittig** [comment]
released in `1.3.0`
